apiVersion: v1
kind: Secret
metadata:
  name: laradock-app-secrets
type: Opaque
stringData:
  DB_PASSWORD: "root"
  REDIS_PASSWORD: "secret" # Leave empty if not used
  APP_KEY: "base64:mBUSNGtDq+6C5z3kNnJDXhaeN9k2GZeJVeKI9CvupDg="
