
name: Build and Push to Docker Hub

on:
  # 1. Manual Trigger (Bitbucket Style)
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version Tag (e.g. 1.0.2)'
        required: true
        default: 'latest'

  # 2. Automatic Trigger (on every push to main)
  # push:
  #   branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (for faster builds & caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub using your Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build test image
      - name: Build image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: app:test

      # Run the tests INSIDE the image we just built
      - name: Run tests in container
        run: |
          docker run --rm \
            -e APP_ENV=testing \
            app:test ./vendor/bin/phpunit

      # Build and Push the image
      - name: Build and Push laradock App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          # We tag it with the manual input OR 'latest' if run automatically
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/laradock:${{ github.event.inputs.version_tag || 'latest' }}
            ${{ secrets.DOCKERHUB_USERNAME }}/laradock:${{ github.sha }}
          # Pass your build args for the USER_ID (defaulting to 1000)
          build-args: |
            USER_ID=1000
            GROUP_ID=1000
